### ISSUE TITLE
 STF has an error when I run mvn clean test

### ISSUE THREAD

**Issue by 5pac** [email2vimalraj/appium-stf-example#8]
I successfully started STF,and I run "mvn clean test",

[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.vimalselvam:appium-stf-example >-----------------
[INFO] Building appium-stf-example 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ appium-stf-example ---
[INFO] Deleting /usr/local/stf/test_code/appium-stf-example/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ appium-stf-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /usr/local/stf/test_code/appium-stf-example/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ appium-stf-example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 2 source files to /usr/local/stf/test_code/appium-stf-example/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ appium-stf-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ appium-stf-example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /usr/local/stf/test_code/appium-stf-example/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ appium-stf-example ---
[INFO] Surefire report directory: /usr/local/stf/test_code/appium-stf-example/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.vimalselvam.stf.AndroidTest
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@626b2d4a
Dec 19, 2018 6:45:21 PM com.vimalselvam.DeviceApi addDeviceToUser
INFO: The device <68UDU17A19008448> is locked successfully
[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 24 ms - 83
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/usr/local/stf/test_code/appium-stf-example/src/test/resources/ApiDemos-debug.apk","platformName":"Android","udid":"68UDU17A19008448","deviceName":"ANDROID"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/usr/local/stf/test_code/appium-stf-example/src/test/resources/ApiDemos-debug.apk","platformName":"Android","udid":"68UDU17A19008448","deviceName":"ANDROID"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1545216324591 (18:45:24 GMT+0800 (CST))
[Appium] Creating new AndroidDriver (v1.40.1) session
[Appium] Capabilities:
[Appium]   app: '/usr/local/stf/test_code/appium-stf-example/src/test/resources/ApiDemos-debug.apk'
[Appium]   platformName: 'Android'
[Appium]   udid: '68UDU17A19008448'
[Appium]   deviceName: 'ANDROID'
[debug] [BaseDriver] W3C capabilities [] and MJSONWP desired capabilities  were provided
[BaseDriver] Falling back to MJSONWP desired capabilities
[BaseDriver] Session created with session id: cc5aec51-0f69-41ac-b9d3-7bd954326caf
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_191
[ADB] Checking whether adb is present
[ADB] Found 6 'build-tools' folders under '/usr/local/stf/android-sdk-linux' (newest first):
[ADB]     /usr/local/stf/android-sdk-linux/build-tools/28.0.3
[ADB]     /usr/local/stf/android-sdk-linux/build-tools/27.0.0
[ADB]     /usr/local/stf/android-sdk-linux/build-tools/24.0.2
[ADB]     /usr/local/stf/android-sdk-linux/build-tools/24.0.1
[ADB]     /usr/local/stf/android-sdk-linux/build-tools/24.0.0
[ADB]     /usr/local/stf/android-sdk-linux/build-tools/23.0.3
[ADB] Using adb from /usr/local/stf/android-sdk-linux/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: Error: Could not find a connected Android device.
[MJSONWP]     at getDevices (/usr/local/stf/node-v9.11.2-linux-x64/lib/node_modules/appium/node_modules/_appium-adb@6.29.1@appium-adb/lib/tools/system-calls.js:195:13)
[MJSONWP]     at getDevices (/usr/local/stf/node-v9.11.2-linux-x64/lib/node_modules/appium/node_modules/_appium-adb@6.29.1@appium-adb/lib/tools/system-calls.js:212:20)
[MJSONWP]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 24704 ms - 179
[HTTP] 
Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 28.285 sec <<< FAILURE!
setup(com.vimalselvam.stf.AndroidTest)  Time elapsed: 28.183 sec  <<< FAILURE!
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 24.83 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-139-generic', java.version: '1.8.0_191'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:51)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:47)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:97)
	at com.vimalselvam.stf.AndroidTest.setup(AndroidTest.java:61)

Results :

Failed tests:   setup(com.vimalselvam.stf.AndroidTest): An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device. (WARNING: The server did not provide any stacktrace information)(..)

Tests run: 4, Failures: 1, Errors: 0, Skipped: 3

And STF's log is

FTL/util:lifecycle 30122 [*] Tracker had an error Error: Connection closed
    at /usr/local/stf/stf-master/node_modules/adbkit/lib/adb/tracker.js:21:13
    at tryCatcher (/usr/local/stf/stf-master/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/usr/local/stf/stf-master/node_modules/adbkit/node_modules/bluebird/js/main/catch_filter.js:40:36)
    at CatchFilter.tryCatcher (/usr/local/stf/stf-master/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/stf/stf-master/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/stf/stf-master/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/local/stf/stf-master/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/stf/stf-master/node_modules/adbkit/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/stf/stf-master/node_modules/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/stf/stf-master/node_modules/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
2018-12-19T10:58:41.415Z FTL/util:lifecycle 30122 [*] Shutting down due to fatal error
2018-12-19T10:58:41.419Z FTL/cli:local 30086 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/stf/stf-master/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)

Can you tell me the solution? thanks

**Comment by deolas** [comment]
I am also getting same issue when I run "mvn clean test". Is there any solution for this.

**Comment by imran-abbas1** [comment]
Anyone got the solution to the above problem?

**Comment by 4nif** [comment]
Getting same issuen when, @email2vimalraj any idea on this problem?

**Comment by CarpCap** [comment]
Me too
